### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by thecaligarmo** [mtorpey/pypersist#13]
Less of an issue, but more of a severe annoyance. Whenever we try and save something, there is a print that is executed. Although sometimes this is short and so doesn't get in the way, if we are cacheing large items, this can fill up the whole screen and make the terminal illegible. I think the error is arising from pypersist/diskcache.py:105 where it says: `print(to_write)`. Is there a way to remove this line and/or make it optional?

**Comment by mtorpey** [comment]
Hi there!

Yep, mandatory print statements were probably a bad idea.  Ideally this should be configurable, probably via a global variable called something like `VERBOSE` in `__init__.py` (see also Issue #5).

Unfortunately, with teaching commitments I don't think I'll be working on this very soon.  But I'd welcome a pull request! :)

Thanks for flagging this up.

**Comment by mtorpey** [comment]
Fixed by #14.  Thanks again!
